
const STORAGE_PREFIX = 'jumpforge_stable_v2_20260427';
const STORAGE = {
  ui: STORAGE_PREFIX + '_ui',
  checks: STORAGE_PREFIX + '_checks',
  notes: STORAGE_PREFIX + '_notes',
  tracker: STORAGE_PREFIX + '_tracker',
  maxes: STORAGE_PREFIX + '_maxes',
  settings: STORAGE_PREFIX + '_settings'
};
const DAY_SHORT = ['Mon','Tue','Wed','Thu','Fri','Sat'];
const DAY_LONG = ['Monday','Tuesday','Wednesday','Thursday','Friday','Saturday'];
const DEFAULT_UI = { activeView:'home', activeWeek:1, activeDay:0, browseWeek:1, browseDay:0 };
const DEFAULT_SETTINGS = { startDate:'', autoFollow:true };
const DEFAULT_MAXES = { backSquat:'', frontSquat:'', powerClean:'', powerSnatch:'', rdl:'' };
const monthDefs = [
  { month:1, weeks:[1,2,3,4], title:'Volume Building', subtitle:'General strength, athletic work, and tissue capacity.', split:{low:35,max:5}, deload:4 },
  { month:2, weeks:[5,6,7,8], title:'Intensification', subtitle:'More specific lifting and cleaner explosive work.', split:{low:30,max:10}, deload:8 },
  { month:3, weeks:[9,10,11,12], title:'Absolute Strength', subtitle:'Heavy squats, hard pulls, and eccentric priming.', split:{low:25,max:15}, deload:12 },
  { month:4, weeks:[13,14,15,16], title:'Fast Bars + Eccentrics', subtitle:'Move weight fast and build elastic strength.', split:{low:20,max:20}, deload:16 },
  { month:5, weeks:[17,18,19,20], title:'Speed Strength', subtitle:'Fast bars, medball work, and controlled shock loading.', split:{low:20,max:20}, deload:20 },
  { month:6, weeks:[21,22,23,24], title:'Peak Specificity', subtitle:'High-quality jumps and fresh legs.', split:{low:20,max:20}, deload:24 }
];
const lib = {
  'Hang Power Clean':{d:'Catch the bar above parallel with a fast vertical pull from the hang.',w:'Builds power output and crisp force production.',c:['Push through the floor','Keep the bar close','Catch fast'],a:['Early arm pull','Jumping forward','Soft catch']},
  'Back Squat':{d:'Strong bilateral squat with full-foot pressure and controlled depth.',w:'Drives lower-body strength that supports vertical jump output.',c:['Brace hard','Knees over toes','Drive up with intent'],a:['Heels lifting','Chest collapsing','Grinding every rep']},
  'RDL':{d:'Hip hinge with tension through the hamstrings and glutes.',w:'Builds posterior-chain strength for jumping and landing.',c:['Push hips back','Keep lats tight','Own the stretch'],a:['Rounding the back','Turning it into a squat','Bouncing']},
  'Bulgarian Split Squat':{d:'Rear foot elevated split squat focused on front-leg force.',w:'Builds single-leg strength and cleans up side-to-side asymmetry.',c:['Stay tall','Load the front leg','Control the bottom'],a:['Falling forward','Back-leg push-off','Rushed reps']},
  'Standing Calf Raise':{d:'Controlled calf raise with a pause at the top.',w:'Improves ankle stiffness and lower-leg strength.',c:['Push through the big toe','Pause at the top','Lower under control'],a:['Short reps','Rolling ankles','Mindless bouncing']},
  'Hanging Knee Raise':{d:'Raise the knees with a braced trunk and minimal swing.',w:'Supports trunk control and safer force transfer.',c:['Tuck under control','Own the bottom','Ribs down'],a:['Wild swinging','Shrugging up','Using momentum']},
  'Push Press':{d:'Dip straight and drive the bar overhead fast.',w:'Teaches coordinated power transfer from legs to upper body.',c:['Dip vertical','Punch up fast','Lock out clean'],a:['Too deep a dip','Slow press','Leaning back hard']},
  'Front Squat':{d:'Front-loaded squat that challenges posture and quad strength.',w:'Builds upright force production that carries to jumping.',c:['Elbows high','Brace 360','Sit between the hips'],a:['Dropping elbows','Folding forward','Losing heel pressure']},
  'Hip Thrust':{d:'Drive the hips up explosively while keeping the trunk stacked.',w:'Targets glute force production and explosive hip extension.',c:['Drive through midfoot','Pause at the top','Stay stacked'],a:['Overarching the back','Cutting the range short','Sloppy setup']},
  'Reverse Lunge':{d:'Step back under control and load the lead leg.',w:'Builds unilateral force and deceleration control.',c:['Step back smoothly','Stay balanced','Push through the front leg'],a:['Slamming the back knee','Wobbling','Too much forward lean']},
  'High Pull':{d:'Explosive pull with elbows high and outside while staying tall.',w:'Trains vertical force and fast bar speed.',c:['Finish tall','Keep bar close','Elbows high'],a:['Muscling the bar','Bending the arms early','Jumping forward']},
  'Tempo Run':{d:'Submax running used for work capacity and recovery support.',w:'Builds conditioning without frying your nervous system.',c:['Stay relaxed','Smooth rhythm','Finish in control'],a:['Sprinting','Tensing up','Competing on recovery work']},
  'Power Clean':{d:'Explosive clean variation focused on speed and a fast turnover.',w:'One of the best weight-room tools for lower-body power.',c:['Push then pull','Fast elbows','Catch tall'],a:['Pulling early with the arms','Slow turnover','Heavy ugly reps']},
  'Clean Pull':{d:'Aggressive pull patterned after the clean but without the catch.',w:'Builds force and safely overloads the clean pattern.',c:['Stay over the bar','Extend violently','Keep bar path close'],a:['Leaning back too early','Yanking with arms','Looping the bar away']},
  'Nordic Curl':{d:'Control the lowering phase as long as possible.',w:'Builds eccentric hamstring strength and resilience.',c:['Brace glutes','Control down','Keep hips extended'],a:['Breaking at the hips','Dropping instantly','Neck cranking']},
  'Pause Back Squat':{d:'Back squat with a deliberate pause in the bottom.',w:'Improves force from static positions and deep-range control.',c:['Own the pause','Stay braced','Explode up'],a:['Relaxing at the bottom','Losing tension','Shifting to toes']},
  'Jump Squat':{d:'Light loaded jump focused on speed and clean landing.',w:'Targets fast force production with jump-specific intent.',c:['Move violently','Land softly','Reset each rep'],a:['Using too much weight','Grinding','Sloppy landings']},
  'Power Snatch':{d:'Fast, light Olympic lift emphasizing speed and crisp turnover.',w:'Develops bar speed and athletic coordination.',c:['Finish tall','Stay stacked','Punch under fast'],a:['Heavy slow reps','Wide looping bar','Crashing the catch']},
  'Sprint':{d:'Short high-quality sprint with full recovery between reps.',w:'Improves rate of force development and jump readiness.',c:['Stay crisp','Drive the knee','Full recovery'],a:['Fatigue sprints','Overstriding','Too much volume']},
  'Approach Jump':{d:'Game-speed approach jump or dunk attempt with maximal intent.',w:'Directly trains the exact skill you want to peak.',c:['Attack the plant','Use the arms','Full effort'],a:['Too many contacts','Half-speed reps','Jumping while flat']}
};

function clone(v){ return JSON.parse(JSON.stringify(v)); }
function safeParse(v, fallback){ try { const p = JSON.parse(v); return p == null ? fallback : p; } catch { return fallback; } }
function objectOnly(v, fallback){ return v && typeof v === 'object' && !Array.isArray(v) ? v : fallback; }
function clamp(n,min,max){ return Math.max(min, Math.min(max, n)); }
function weekDef(n){ return monthDefs.find(m => m.weeks.indexOf(n) !== -1); }
function exercise(name, sets, reps, intensity, extra){ extra = extra || {}; const e = lib[name] || {d:'Structured training movement for this phase.',w:'Included to build the physical qualities needed in this block.',c:['Move clean','Keep quality high','Stop before form breaks'],a:['Sloppy reps','Grinding','Ignoring fatigue']}; return {name:name, sets:sets, reps:reps, intensity:intensity, note:extra.note || '', type:extra.type || 'lift', desc:e.d, why:e.w, cues:e.c, avoid:e.a}; }
function day(day, short, type, focus, exercises){ return { day:day, short:short, type:type, focus:focus, exercises:exercises }; }
function buildWeek(num){
  const def = weekDef(num); const p = def.weeks.indexOf(num); const deload = def.deload === num; const days = [];
  if (def.month === 1) {
    const pct = deload ? '60–65%' : ['65%','67.5%','70%'][Math.min(p,2)];
    days.push(day('Monday','Mon','Lift A','Volume strength and clean mechanics.',[exercise('Hang Power Clean','5','4',pct),exercise('Back Squat','4',deload?'6':'8',pct),exercise('RDL','3',deload?'8':'10','moderate'),exercise('Bulgarian Split Squat','3','8/leg','controlled'),exercise('Standing Calf Raise','4','12','controlled'),exercise('Hanging Knee Raise','3','12','bodyweight')]));
    days.push(day('Tuesday','Tue','Jump + General','Low-effort contacts first, then a few max jumps.',[exercise('Approach Jump','1',(deload?'4':'8')+' total',def.split.max+' min max',{type:'jump',note:'Use '+def.split.low+' min for low-effort pogo hops, line hops, snap-downs, and easy approach work first.'}),exercise('Tempo Run','10','100 m','60–70%',{type:'conditioning'}),exercise('Standing Calf Raise','3','15','light',{note:'Optional extra ankle stiffness work.'})]));
    days.push(day('Wednesday','Wed','Lift B','Front-side strength and upper-body support.',[exercise('Push Press','5','4',pct),exercise('Front Squat','4',deload?'6':'8',pct),exercise('Hip Thrust','4',deload?'8':'10','moderate'),exercise('Reverse Lunge','3','10/leg','controlled')]));
    days.push(day('Thursday','Thu','Jump + Tempo','General athletic day with easy running and circuits.',[exercise('Approach Jump','1',(deload?'4':'8')+' total',def.split.max+' min max',{type:'jump',note:'Low-effort jump block first for '+def.split.low+' min.'}),exercise('Tempo Run',deload?'6':'8–10',deload?'80 m':'100–120 m','easy'),exercise('Reverse Lunge','3','10/leg','light')]));
    days.push(day('Friday','Fri','Lift C','Posterior chain and paused strength.',[exercise('High Pull','5','4',pct),exercise('Pause Back Squat','4',deload?'6':'8',pct),exercise('RDL','3','8','controlled'),exercise('Standing Calf Raise','4','15','controlled')]));
    days.push(day('Saturday','Sat','Recovery','Mobility, walking, and easy recovery only.',[exercise('Tempo Run','1','20–30 min walk or bike','easy',{type:'recovery',note:'Mobility and ankle/hip work after.'})]));
  } else if (def.month === 2) {
    const squatPct = deload ? '70%' : ['75%','77.5%','80–82%'][Math.min(p,2)]; const cleanPct = deload ? '70%' : ['75%','77.5%','80–82.5%'][Math.min(p,2)];
    days.push(day('Monday','Mon','Lift A','Heavier pulling and lower-volume strength.',[exercise('Clean Pull',deload?'3':'6','3',deload?'85%':['90%','90%','92.5%'][Math.min(p,2)]),exercise('Back Squat',deload?'3':'4',deload?'5':'6',squatPct),exercise('RDL','3','8','moderate'),exercise('Nordic Curl','3','4–6','eccentric'),exercise('Standing Calf Raise','4','10','controlled')]));
    days.push(day('Tuesday','Tue','Jump + Circuit','Specific jumps plus circuit and tempo work.',[exercise('Approach Jump','1','10–12 total',def.split.max+' min max',{type:'jump',note:'Start with '+def.split.low+' min of low hurdle hops, penultimate drills, and easy broad jumps.'}),exercise('Tempo Run',deload?'6':'8',deload?'80 m':'100 m','65–70%')]));
    days.push(day('Wednesday','Wed','Lift B','Specific power work and front squat strength.',[exercise('Power Clean',deload?'3':'5','3',cleanPct),exercise('Front Squat',deload?'3':'4',deload?'5':'6',squatPct),exercise('Hip Thrust','3','8','moderate'),exercise('Reverse Lunge','3','8/leg','controlled')]));
    days.push(day('Thursday','Thu','Jump + Tempo','Specific jump day with controlled conditioning.',[exercise('Approach Jump','1','10–12 total',def.split.max+' min max',{type:'jump',note:'Low-effort jump work for '+def.split.low+' min first.'}),exercise('Tempo Run',deload?'4':'6',deload?'100 m':'150 m','65–70%')]));
    days.push(day('Friday','Fri','Lift C','Block pulls and paused squat emphasis.',[exercise('Clean Pull',deload?'3':'5','3',deload?'85%':['90%','92.5%','95%'][Math.min(p,2)]),exercise('Pause Back Squat',deload?'3':'4',deload?'5':'6',deload?'70%':['77%','80%','82%'][Math.min(p,2)]),exercise('Nordic Curl','3','4','eccentric')]));
    days.push(day('Saturday','Sat','Recovery','Easy recovery and mobility.',[exercise('Tempo Run','1','20–30 min walk or bike','easy',{type:'recovery'})]));
  } else if (def.month === 3) {
    const cleanPct = deload ? '95%' : ['105%','107.5%','110%'][Math.min(p,2)]; const squatPct = deload ? '75–80%' : ['85%','86–87%','88–90%'][Math.min(p,2)];
    days.push(day('Monday','Mon','Lift A','Absolute strength and heavy clean pulls.',[exercise('Clean Pull',deload?'3':'5',deload?'2':'3',cleanPct),exercise('Back Squat',deload?'4':'10','2',squatPct),exercise('RDL','4','6','heavy'),exercise('Nordic Curl','4','4','eccentric')]));
    days.push(day('Tuesday','Tue','Jump + Tempo','Sand or low-impact jump circuits with controlled max efforts.',[exercise('Approach Jump','1','8–10 total',def.split.max+' min max',{type:'jump',note:'Use '+def.split.low+' min for sand pogo hops, broad jumps, bounds, and landing practice.'}),exercise('Tempo Run','6',deload?'100 m':'200 m','70%')]));
    days.push(day('Wednesday','Wed','Lift B','Heavy front squat with eccentric single-leg work.',[exercise('Power Clean',deload?'3':'6','2',deload?'75%':['80%','82.5%','85%'][Math.min(p,2)]),exercise('Front Squat',deload?'3':'6','3',deload?'75%':['82%','84%','86%'][Math.min(p,2)]),exercise('Hip Thrust','3','6–8','moderate'),exercise('Reverse Lunge','3','6/leg','4 sec down')]));
    days.push(day('Thursday','Thu','Jump + Circuit','Jump circuit plus controlled tempo.',[exercise('Approach Jump','1','8–10 total',def.split.max+' min max',{type:'jump'}),exercise('Tempo Run',deload?'6':'8',deload?'100 m':'120–150 m','70%')]));
    days.push(day('Friday','Fri','Lift C','Heavy doubles and posterior-chain support.',[exercise('Clean Pull',deload?'3':'5','2',cleanPct),exercise('Back Squat',deload?'4':'8','2',deload?'78%':['88%','89%','90%'][Math.min(p,2)]),exercise('RDL','3','5','pause below knee'),exercise('Standing Calf Raise','4','10','controlled')]));
    days.push(day('Saturday','Sat','Recovery','Extra sleep, mobility, and easy walking.',[exercise('Tempo Run','1','20 min walk','easy',{type:'recovery'})]));
  } else if (def.month === 4) {
    days.push(day('Monday','Mon','Lift A','Fast cleans and eccentric overload theme.',[exercise('Power Clean',deload?'3':'6',deload?'2':'1–2',deload?'75–80%':['85%','87–88%','90–92%'][Math.min(p,2)]),exercise('Back Squat',deload?'3':'4',deload?'3':'2',deload?'70%':'110–115% eccentric',{note:'Use safe assisted eccentrics only if equipment is available.'}),exercise('RDL','3','5','drop RDL'),exercise('Standing Calf Raise','4','10','high velocity')]));
    days.push(day('Tuesday','Tue','Jump + Medball','Highest jump specificity so far.',[exercise('Approach Jump','1','10–12 total',def.split.max+' min max',{type:'jump',note:'Low-effort warm-up jumps for '+def.split.low+' min before max attempts.'}),exercise('Sprint','4','medball throw sets','explosive',{type:'power',note:'Use overhead throws and scoop tosses.'})]));
    days.push(day('Wednesday','Wed','Lift B','Specific pulling pattern and front squat support.',[exercise('Power Clean',deload?'3':'6','2',deload?'70–75%':['78%','80–82%','82–85%'][Math.min(p,2)]),exercise('Front Squat',deload?'3':'5','3',deload?'70%':['80%','82%','84–85%'][Math.min(p,2)]),exercise('Hip Thrust','3','5–6','moderate')]));
    days.push(day('Thursday','Thu','Elastic Day','Low contacts, fast feet, and fresh landings.',[exercise('Approach Jump','1','8–10 total',def.split.max+' min max',{type:'jump'}),exercise('Tempo Run',deload?'4':'6','80 m','60–65%')]));
    days.push(day('Friday','Fri','Lift C','Fast pulls with controlled landing work.',[exercise('High Pull',deload?'3':'5','3',deload?'light':'75–85%'),exercise('Back Squat',deload?'2–3':'3',deload?'3':'2',deload?'light':'110–115% eccentric',{note:'Swap to tempo squat if no eccentric setup exists.'}),exercise('RDL','3','6/leg','single-leg'),exercise('Standing Calf Raise','4','10','controlled')]));
    days.push(day('Saturday','Sat','Recovery','Easy day only.',[exercise('Tempo Run','1','20–30 min walk','easy',{type:'recovery'})]));
  } else if (def.month === 5) {
    days.push(day('Monday','Mon','Lift A','Speed-strength and medball work.',[exercise('Power Snatch',deload?'3':'6','2',deload?'55–60%':['60%','65%','70%'][Math.min(p,2)]),exercise('Back Squat',deload?'3':'6','2',deload?'45–50%':['50%','55%','60%'][Math.min(p,2)],{note:'Speed squat with maximal intent.'}),exercise('Jump Squat','4','3','light'),exercise('Standing Calf Raise','3','12','fast')]));
    days.push(day('Tuesday','Tue','Jump + Regen','Keep jumps crisp and total contacts controlled.',[exercise('Approach Jump','1','8–12 total',def.split.max+' min max',{type:'jump',note:'Use '+def.split.low+' min for ankle hops, snap-downs, and easy approach work.'}),exercise('Tempo Run','1','15 min bike or walk','easy',{type:'recovery'})]));
    days.push(day('Wednesday','Wed','Lift B','Fast cleans and reactive contacts.',[exercise('Power Clean',deload?'3':'6','2',deload?'60%':['65%','67.5%','70%'][Math.min(p,2)]),exercise('Front Squat',deload?'3':'4','3',deload?'65%':['70%','72.5%','75%'][Math.min(p,2)]),exercise('Hip Thrust','3','5','moderate')]));
    days.push(day('Thursday','Thu','Recovery','Core, mobility, and static flexibility.',[exercise('Tempo Run','1','20–30 min recovery work','easy',{type:'recovery'})]));
    days.push(day('Friday','Fri','Lift C','Mix one heavier squat touch with jump intent.',[exercise('Jump Squat',deload?'3':'5','3','light'),exercise('Back Squat',deload?'2':'3','3',deload?'70%':['80%','82.5%','85%'][Math.min(p,2)]),exercise('Approach Jump','1','4–6 total','quality only',{type:'jump'})]));
    days.push(day('Saturday','Sat','Optional','Only jump if you still feel springy.',[exercise('Approach Jump','1','4–6 total','optional',{type:'jump',note:'Skip if legs feel flat.'})]));
  } else {
    days.push(day('Monday','Mon','Sprint + Jump','Acceleration and max jump quality first.',[exercise('Sprint','6','20 m','full recovery'),exercise('Sprint','4','30 m','full recovery'),exercise('Approach Jump','1','8–10 total','max intent',{type:'jump'}),exercise('Back Squat','3','5','55–60%'),exercise('RDL','3','6','55–60%')]));
    days.push(day('Tuesday','Tue','Recovery','Light flush and mobility only.',[exercise('Tempo Run','1','20–30 min walk or bike','easy',{type:'recovery'})]));
    days.push(day('Wednesday','Wed','Plyo + Easy Lift','Reactive work without too much fatigue.',[exercise('Approach Jump','1','6–8 total','quality only',{type:'jump'}),exercise('Front Squat','3','5','50–60%'),exercise('Hip Thrust','2','6','easy')]));
    days.push(day('Thursday','Thu','Recovery','Static flexibility and easy breathing work.',[exercise('Tempo Run','1','15–20 min easy work','easy',{type:'recovery'})]));
    days.push(day('Friday','Fri','Max Jump Day','Best jump day of the week.',[exercise('Approach Jump','1','10–12 total','max intent',{type:'jump'}),exercise('Back Squat','3','4','55–60%'),exercise('RDL','2','6/leg','single-leg')]));
    days.push(day('Saturday','Sat','Optional','Only if fresh.',[exercise('Approach Jump','1','4–6 total','optional',{type:'jump'})]));
  }
  return { week:num, month:def.month, title:def.title, subtitle:def.subtitle, split:def.split, deload:deload, days:days };
}
const PROGRAM = Array.from({length:24}, (_,i)=>buildWeek(i+1));

const state = Object.assign({}, clone(DEFAULT_UI), { checks:{}, notes:{}, tracker:{}, maxes:clone(DEFAULT_MAXES), settings:clone(DEFAULT_SETTINGS) });
const el = {};
let toastTimer = null;

function $(id){ return document.getElementById(id); }
function save(){ localStorage.setItem(STORAGE.ui, JSON.stringify({activeView:state.activeView,activeWeek:state.activeWeek,activeDay:state.activeDay,browseWeek:state.browseWeek,browseDay:state.browseDay})); localStorage.setItem(STORAGE.checks, JSON.stringify(state.checks)); localStorage.setItem(STORAGE.notes, JSON.stringify(state.notes)); localStorage.setItem(STORAGE.tracker, JSON.stringify(state.tracker)); localStorage.setItem(STORAGE.maxes, JSON.stringify(state.maxes)); localStorage.setItem(STORAGE.settings, JSON.stringify(state.settings)); }
function load(){ Object.assign(state, clone(DEFAULT_UI), objectOnly(safeParse(localStorage.getItem(STORAGE.ui), {}), {})); state.checks = objectOnly(safeParse(localStorage.getItem(STORAGE.checks), {}), {}); state.notes = objectOnly(safeParse(localStorage.getItem(STORAGE.notes), {}), {}); state.tracker = objectOnly(safeParse(localStorage.getItem(STORAGE.tracker), {}), {}); state.maxes = Object.assign(clone(DEFAULT_MAXES), objectOnly(safeParse(localStorage.getItem(STORAGE.maxes), {}), {})); state.settings = Object.assign(clone(DEFAULT_SETTINGS), objectOnly(safeParse(localStorage.getItem(STORAGE.settings), {}), {})); if (state.settings.autoFollow && state.settings.startDate) followToday(); }
function followToday(){ const d = resolveToday(); state.activeWeek = d.week; state.activeDay = d.day; state.browseWeek = d.week; state.browseDay = d.day; }
function resolveToday(){ if (!state.settings.startDate) return {week:state.activeWeek, day:state.activeDay}; const start = new Date(state.settings.startDate+'T00:00:00'); const now = new Date(); const diff = Math.max(0, Math.floor((now - start) / 86400000)); return { week: clamp(Math.floor(diff / 7) + 1, 1, 24), day: clamp(diff % 7, 0, 5) }; }
function weekObj(n){ return PROGRAM.find(w => w.week === Number(n)) || PROGRAM[0]; }
function dayObj(w,d){ const wk = weekObj(w); return wk.days[Number(d)] || wk.days[0]; }
function checkKey(w,d,i){ return w+'|'+d+'|'+i; }
function noteKey(w,d){ return w+'|'+d; }
function toast(msg){ el.toast.textContent = msg; el.toast.classList.add('show'); clearTimeout(toastTimer); toastTimer = setTimeout(()=>el.toast.classList.remove('show'), 2200); }
function getDayProgress(w,d){ const day = dayObj(w,d); let done = 0; day.exercises.forEach((_,i)=>{ if (state.checks[checkKey(w,d,i)]) done += 1; }); const total = day.exercises.length; return {done:done,total:total,pct:total?Math.round(done*100/total):0}; }
function getWeekProgress(w){ const wk = weekObj(w); let done = 0, total = 0; wk.days.forEach((day,di)=>day.exercises.forEach((_,i)=>{ total += 1; if (state.checks[checkKey(w,di,i)]) done += 1; })); return {done:done,total:total,pct:total?Math.round(done*100/total):0}; }
function best(field){ const vals = Object.values(state.tracker).map(v => Number(v && v[field])).filter(v => !isNaN(v) && v > 0); return vals.length ? Math.max.apply(null, vals) : null; }
function progress(p){ return '<div class="progress"><span style="width:'+p+'%"></span></div>'; }
function selectedLoad(ex){ if (!ex.intensity || ex.intensity.indexOf('%') === -1) return ''; var m = ex.intensity.match(/(\d+(?:\.\d+)?)%/); if (!m) return ''; var pct = parseFloat(m[1])/100; var max = ''; var n = ex.name.toLowerCase(); if (n.indexOf('front squat') !== -1) max = Number(state.maxes.frontSquat); else if (n.indexOf('squat') !== -1) max = Number(state.maxes.backSquat); else if (n.indexOf('clean') !== -1 && n.indexOf('pull') === -1) max = Number(state.maxes.powerClean); else if (n.indexOf('snatch') !== -1) max = Number(state.maxes.powerSnatch); else if (n.indexOf('rdl') !== -1) max = Number(state.maxes.rdl); return max && !isNaN(max) ? 'Suggested load: ' + Math.round(max*pct) + ' lb' : ''; }
function exerciseCard(ex,w,d,i,withCheck){ var checked = !!state.checks[checkKey(w,d,i)]; var meta = [ex.sets?ex.sets+' sets':'', ex.reps||'', ex.intensity||''].filter(Boolean).join(' • '); var load = selectedLoad(ex); return '<div class="exercise-card '+(checked?'completed':'')+'" data-open-ex="'+w+'|'+d+'|'+i+'">'+(withCheck?('<input class="check" type="checkbox" '+(checked?'checked':'')+' data-check="'+w+'|'+d+'|'+i+'">'):'<div></div>')+'<div class="exercise-main"><h4>'+ex.name+'</h4><div class="exercise-meta">'+(meta||'Tap for details')+'</div>'+(load?'<div class="exercise-note">'+load+'</div>':'')+(ex.note?'<div class="exercise-note">'+ex.note+'</div>':'')+'</div><div class="exercise-cta">Details</div></div>'; }
function renderHome(){ var wk = weekObj(state.activeWeek), dy = dayObj(state.activeWeek, state.activeDay), wp = getWeekProgress(state.activeWeek), dp = getDayProgress(state.activeWeek, state.activeDay); return '<div class="stack">'+
  '<section class="panel section"><div class="badge-row"><span class="badge '+(wk.deload?'warn':'success')+'">'+(wk.deload?'Deload':'Month '+wk.month)+'</span><span class="badge">Jump split '+wk.split.low+'/'+wk.split.max+'</span></div>'+
  '<div class="metric-grid" style="margin-top:12px"><div class="metric"><span class="metric-label">Today</span><div class="metric-value">'+dy.short+'</div><div class="metric-sub">'+dy.type+'</div></div><div class="metric"><span class="metric-label">Week</span><div class="metric-value">'+state.activeWeek+'</div><div class="metric-sub">'+wk.title+'</div></div><div class="metric"><span class="metric-label">Today complete</span><div class="metric-value">'+dp.pct+'%</div><div class="metric-sub">'+dp.done+'/'+dp.total+' items</div></div><div class="metric"><span class="metric-label">Standing PR</span><div class="metric-value">'+(best('standingVertical') ? best('standingVertical')+' in' : '—')+'</div><div class="metric-sub">Approach '+(best('approachJump') ? best('approachJump')+' in' : '—')+'</div></div></div>'+
  '<div style="margin-top:12px">'+progress(wp.pct)+'</div><div class="progress-meta"><span>'+wk.title+'</span><span>'+wk.subtitle+'</span></div><div class="action-row" style="margin-top:12px"><button class="btn primary" data-nav="today">Open today</button><button class="btn secondary" data-nav="program">View week</button></div></section>'+
  '<section class="panel section"><h3>Today’s preview</h3><div class="exercise-list">'+dy.exercises.slice(0,4).map(function(ex,i){ return exerciseCard(ex, state.activeWeek, state.activeDay, i, false); }).join('')+'</div></section></div>'; }
function renderProgram(){ var wk = weekObj(state.browseWeek), dy = dayObj(state.browseWeek, state.browseDay), wp = getWeekProgress(state.browseWeek); return '<div class="stack"><section class="panel section"><div class="action-row" style="justify-content:space-between;align-items:center"><div><h3>Program browser</h3><div class="muted">Week '+wk.week+' • '+wk.title+'</div></div><select id="browseWeekSelect" style="max-width:92px">'+PROGRAM.map(function(w){ return '<option value="'+w.week+'" '+(w.week===state.browseWeek?'selected':'')+'>'+w.week+'</option>'; }).join('')+'</select></div><div style="margin-top:10px">'+progress(wp.pct)+'</div><div class="progress-meta"><span>'+wk.subtitle+'</span><span>'+wp.done+'/'+wp.total+'</span></div></section><section class="panel section"><div class="day-pills">'+wk.days.map(function(d,i){ return '<button class="day-pill '+(i===state.browseDay?'active':'')+'" data-browse-day="'+i+'"><strong>'+d.short+'</strong><span>'+d.type+'</span></button>'; }).join('')+'</div></section><section class="panel section"><div class="badge-row"><span class="badge">'+dy.day+'</span><span class="badge">'+dy.type+'</span><span class="badge">'+getDayProgress(state.browseWeek,state.browseDay).pct+'%</span></div><p class="muted" style="margin-top:10px">'+dy.focus+'</p><div class="exercise-list" style="margin-top:10px">'+dy.exercises.map(function(ex,i){ return exerciseCard(ex, state.browseWeek, state.browseDay, i, false); }).join('')+'</div></section></div>'; }
function renderToday(){ var wk = weekObj(state.activeWeek), dy = dayObj(state.activeWeek, state.activeDay), dp = getDayProgress(state.activeWeek,state.activeDay), note = state.notes[noteKey(state.activeWeek,state.activeDay)] || { readiness:7, note:'' }; return '<div class="stack"><section class="panel section"><div class="day-pills">'+wk.days.map(function(d,i){ return '<button class="day-pill '+(i===state.activeDay?'active':'')+'" data-active-day="'+i+'"><strong>'+d.short+'</strong><span>'+d.type+'</span></button>'; }).join('')+'</div></section><section class="panel section"><div class="badge-row"><span class="badge">'+dy.day+'</span><span class="badge">'+dy.type+'</span><span class="badge">'+dp.done+'/'+dp.total+'</span></div><p class="muted" style="margin-top:10px">'+dy.focus+'</p><div style="margin-top:10px">'+progress(dp.pct)+'</div><div class="progress-meta"><span>Session progress</span><span>'+dp.pct+'%</span></div></section><section class="panel section"><h3>Jump timer</h3><div class="timer"><div class="timer-phase">Session split</div><div class="timer-time">'+wk.split.low+':00 / '+wk.split.max+':00</div><div class="timer-sub">Low-effort / max-effort minutes for this week.</div><div class="segment"><div class="segment-label"><span>Low effort</span><span>'+wk.split.low+' min</span></div>'+progress(Math.round((wk.split.low/(wk.split.low+wk.split.max))*100))+'</div><div class="segment"><div class="segment-label"><span>Max effort</span><span>'+wk.split.max+' min</span></div>'+progress(Math.round((wk.split.max/(wk.split.low+wk.split.max))*100))+'</div></div></section><section class="panel section"><h3>Workout</h3><div class="exercise-list">'+dy.exercises.map(function(ex,i){ return exerciseCard(ex, state.activeWeek, state.activeDay, i, true); }).join('')+'</div></section><section class="panel section"><h3>Session notes</h3><div class="grid2"><label><span>Readiness (1–10)</span><input id="todayReadiness" type="number" min="1" max="10" value="'+(note.readiness || 7)+'"></label><div></div></div><label style="display:block;margin-top:10px"><span>Notes</span><textarea id="todayNote">'+(note.note || '')+'</textarea></label><div class="action-row" style="margin-top:10px"><button class="btn primary" id="saveTodayNoteBtn">Save note</button><button class="btn ghost" id="resetTodayBtnInner">Reset checks</button></div></section></div>'; }
function renderTracker(){ var entry = objectOrBlank(state.tracker[state.activeWeek]); var history = Object.keys(state.tracker).sort(function(a,b){ return Number(a)-Number(b); }); return '<div class="stack"><section class="panel section"><h3>Weekly tracker</h3><p class="muted">Log one entry each week so you can track bounce, bodyweight, and recovery.</p><div class="grid2"><label><span>Bodyweight</span><input id="trackBodyweight" type="number" value="'+(entry.bodyweight || '')+'"></label><label><span>Standing vertical</span><input id="trackStanding" type="number" value="'+(entry.standingVertical || '')+'"></label><label><span>Approach jump</span><input id="trackApproach" type="number" value="'+(entry.approachJump || '')+'"></label><label><span>Sleep hours</span><input id="trackSleep" type="number" step="0.1" value="'+(entry.sleep || '')+'"></label><label><span>Leg feel (1–10)</span><input id="trackLegFeel" type="number" min="1" max="10" value="'+(entry.legFeel || '')+'"></label><label><span>Readiness (1–10)</span><input id="trackReadiness" type="number" min="1" max="10" value="'+(entry.readiness || '')+'"></label></div><label style="display:block;margin-top:10px"><span>Notes</span><textarea id="trackNotes">'+(entry.notes || '')+'</textarea></label><div class="action-row" style="margin-top:10px"><button id="saveTrackerBtn" class="btn primary">Save week '+state.activeWeek+'</button><button id="clearTrackerBtn" class="btn ghost">Clear week</button></div></section><section class="panel section"><h3>Saved history</h3><div class="history-list">'+(history.length ? history.map(function(k){ var it = objectOrBlank(state.tracker[k]); return '<div class="history-item"><div class="badge-row"><span class="badge">Week '+k+'</span>'+(it.sleep?'<span class="badge">'+it.sleep+' hr sleep</span>':'')+'</div><div class="muted" style="margin-top:8px">'+(it.bodyweight?('BW '+it.bodyweight+' lb'):'BW —')+' • '+(it.standingVertical?('Standing '+it.standingVertical+' in'):'Standing —')+' • '+(it.approachJump?('Approach '+it.approachJump+' in'):'Approach —')+' • '+(it.legFeel?('Leg feel '+it.legFeel+'/10'):'Leg feel —')+'</div></div>'; }).join('') : '<div class="empty">No tracker entries saved yet.</div>')+'</div></section></div>'; }
function renderSettings(){ return '<div class="stack"><section class="panel section"><h3>Program calendar</h3><div class="settings-grid"><label><span>Program start date</span><input id="startDateInput" type="date" value="'+(state.settings.startDate || '')+'"></label><label><span>Auto-follow current day</span><select id="autoFollowSelect"><option value="true" '+(state.settings.autoFollow?'selected':'')+'>On</option><option value="false" '+(!state.settings.autoFollow?'selected':'')+'>Off</option></select></label></div><div class="action-row" style="margin-top:10px"><button id="saveSettingsBtn" class="btn primary">Save calendar</button></div></section><section class="panel section"><h3>Training maxes</h3><div class="grid2"><label><span>Back squat</span><input id="maxBackSquat" type="number" value="'+state.maxes.backSquat+'"></label><label><span>Front squat</span><input id="maxFrontSquat" type="number" value="'+state.maxes.frontSquat+'"></label><label><span>Power clean</span><input id="maxPowerClean" type="number" value="'+state.maxes.powerClean+'"></label><label><span>Power snatch</span><input id="maxPowerSnatch" type="number" value="'+state.maxes.powerSnatch+'"></label><label><span>RDL</span><input id="maxRDL" type="number" value="'+state.maxes.rdl+'"></label></div><div class="action-row" style="margin-top:10px"><button id="saveMaxesBtn" class="btn primary">Save maxes</button></div></section><section class="panel section"><h3>Data</h3><div class="action-row"><button id="exportBtn" class="btn secondary">Export JSON</button><button id="importBtn" class="btn ghost">Import JSON</button><button id="resetDataBtn" class="btn danger">Reset all</button></div><p class="muted" style="margin-top:10px">This build uses a fresh storage version so it ignores broken data from older test versions.</p></section></div>'; }
function objectOrBlank(v){ return v && typeof v === 'object' ? v : {}; }
function renderView(name){ if (name === 'home') $('homeView').innerHTML = renderHome(); if (name === 'program') $('programView').innerHTML = renderProgram(); if (name === 'today') $('todayView').innerHTML = renderToday(); if (name === 'tracker') $('trackerView').innerHTML = renderTracker(); if (name === 'settings') $('settingsView').innerHTML = renderSettings(); }
function renderAll(){ ['home','program','today','tracker','settings'].forEach(function(v){ try { renderView(v); } catch(err) { console.error('render '+v+' failed', err); var target = $(v + 'View'); if (target) target.innerHTML = '<div class="panel section"><div class="empty">'+v.charAt(0).toUpperCase()+v.slice(1)+' failed to render.</div></div>'; } }); bindStatefulControls(); updateFocus(); }
function updateFocus(){ var wk = weekObj(state.activeWeek), dy = dayObj(state.activeWeek, state.activeDay), dp = getDayProgress(state.activeWeek, state.activeDay); $('focusTitle').textContent = 'Week ' + state.activeWeek + ' • ' + dy.short; $('focusSubtitle').textContent = wk.subtitle + ' ' + dy.focus + (dp.pct ? ' ' + dp.pct + '% complete today.' : ''); $('weekSelect').value = String(state.activeWeek); $('daySelect').value = String(state.activeDay); }
function switchView(v){ state.activeView = v; document.querySelectorAll('.view').forEach(function(node){ node.classList.toggle('active', node.id === v + 'View'); }); document.querySelectorAll('.tab').forEach(function(node){ node.classList.toggle('active', node.getAttribute('data-nav') === v); }); renderView(v); bindStatefulControls(); save(); $('viewContainer').scrollTo({top:0,behavior:'smooth'}); }
function bindStatefulControls(){ var bw = $('browseWeekSelect'); if (bw) bw.onchange = function(){ state.browseWeek = Number(this.value); state.browseDay = 0; save(); renderView('program'); bindStatefulControls(); };
  var sbtn = $('saveTodayNoteBtn'); if (sbtn) sbtn.onclick = function(){ state.notes[state.activeWeek+'|'+state.activeDay] = { readiness: $('todayReadiness').value, note: $('todayNote').value.trim() }; save(); toast('Today’s note saved.'); };
  var rbtn = $('resetTodayBtnInner'); if (rbtn) rbtn.onclick = function(){ var d = dayObj(state.activeWeek, state.activeDay); d.exercises.forEach(function(_,i){ delete state.checks[checkKey(state.activeWeek,state.activeDay,i)]; }); save(); renderView('today'); bindStatefulControls(); toast('Today’s checks reset.'); };
  var saveTrack = $('saveTrackerBtn'); if (saveTrack) saveTrack.onclick = function(){ state.tracker[state.activeWeek] = { bodyweight:$('trackBodyweight').value, standingVertical:$('trackStanding').value, approachJump:$('trackApproach').value, sleep:$('trackSleep').value, legFeel:$('trackLegFeel').value, readiness:$('trackReadiness').value, notes:$('trackNotes').value.trim() }; save(); renderView('tracker'); bindStatefulControls(); renderView('home'); toast('Week '+state.activeWeek+' saved.'); };
  var clearTrack = $('clearTrackerBtn'); if (clearTrack) clearTrack.onclick = function(){ delete state.tracker[state.activeWeek]; save(); renderView('tracker'); bindStatefulControls(); renderView('home'); toast('Week cleared.'); };
  var saveSet = $('saveSettingsBtn'); if (saveSet) saveSet.onclick = saveSettings;
  var dateInput = $('startDateInput'); if (dateInput){ dateInput.onchange = saveSettings; dateInput.onblur = saveSettings; }
  var autoFollow = $('autoFollowSelect'); if (autoFollow) autoFollow.onchange = saveSettings;
  var saveMax = $('saveMaxesBtn'); if (saveMax) saveMax.onclick = function(){ state.maxes.backSquat = $('maxBackSquat').value; state.maxes.frontSquat = $('maxFrontSquat').value; state.maxes.powerClean = $('maxPowerClean').value; state.maxes.powerSnatch = $('maxPowerSnatch').value; state.maxes.rdl = $('maxRDL').value; save(); renderView('today'); bindStatefulControls(); renderView('home'); toast('Training maxes saved.'); };
  var exportBtn = $('exportBtn'); if (exportBtn) exportBtn.onclick = exportData;
  var importBtn = $('importBtn'); if (importBtn) importBtn.onclick = function(){ $('importInput').click(); };
  var resetBtn = $('resetDataBtn'); if (resetBtn) resetBtn.onclick = resetData;
}
function saveSettings(){ state.settings.startDate = $('startDateInput') ? $('startDateInput').value : state.settings.startDate; state.settings.autoFollow = $('autoFollowSelect') ? $('autoFollowSelect').value === 'true' : state.settings.autoFollow; if (state.settings.autoFollow && state.settings.startDate) followToday(); save(); renderView('settings'); bindStatefulControls(); updateFocus(); renderView('home'); renderView('program'); renderView('today'); toast('Calendar saved.'); }
function exportData(){ var data = { ui:{activeView:state.activeView,activeWeek:state.activeWeek,activeDay:state.activeDay,browseWeek:state.browseWeek,browseDay:state.browseDay}, checks:state.checks, notes:state.notes, tracker:state.tracker, maxes:state.maxes, settings:state.settings }; var blob = new Blob([JSON.stringify(data,null,2)], {type:'application/json'}); var url = URL.createObjectURL(blob); var a = document.createElement('a'); a.href = url; a.download = 'jumpforge-backup.json'; a.click(); URL.revokeObjectURL(url); toast('Backup exported.'); }
function resetData(){ if (!window.confirm('Reset all local app data?')) return; Object.keys(STORAGE).forEach(function(k){ localStorage.removeItem(STORAGE[k]); }); Object.assign(state, clone(DEFAULT_UI)); state.checks = {}; state.notes = {}; state.tracker = {}; state.maxes = clone(DEFAULT_MAXES); state.settings = clone(DEFAULT_SETTINGS); populateSelects(); renderAll(); switchView('home'); toast('All local data reset.'); }
function importData(file){ var fr = new FileReader(); fr.onload = function(){ try { var p = JSON.parse(fr.result); Object.assign(state, clone(DEFAULT_UI), objectOnly(p.ui || {}, {})); state.checks = objectOnly(p.checks || {}, {}); state.notes = objectOnly(p.notes || {}, {}); state.tracker = objectOnly(p.tracker || {}, {}); state.maxes = Object.assign(clone(DEFAULT_MAXES), objectOnly(p.maxes || {}, {})); state.settings = Object.assign(clone(DEFAULT_SETTINGS), objectOnly(p.settings || {}, {})); save(); populateSelects(); renderAll(); switchView(state.activeView || 'home'); toast('Backup imported.'); } catch(err) { console.error(err); toast('Import failed.'); } }; fr.readAsText(file); }

function muscleListForExercise(name){
  var n = String(name || '').toLowerCase();
  if (n.indexOf('jump') > -1) return ['Quads','Glutes','Calves','Core'];
  if (n.indexOf('sprint') > -1 || n.indexOf('tempo run') > -1) return ['Quads','Calves','Hip Flexors'];
  if (n.indexOf('split squat') > -1 || n.indexOf('lunge') > -1) return ['Quads','Glutes','Adductors','Core'];
  if (n.indexOf('front squat') > -1 || n.indexOf('back squat') > -1 || n.indexOf('squat') > -1) return ['Quads','Glutes','Core'];
  if (n.indexOf('rdl') > -1 || n.indexOf('hinge') > -1) return ['Hamstrings','Glutes','Lower Back'];
  if (n.indexOf('hip thrust') > -1) return ['Glutes','Hamstrings','Core'];
  if (n.indexOf('calf') > -1) return ['Calves'];
  if (n.indexOf('nordic') > -1) return ['Hamstrings','Glutes'];
  if (n.indexOf('knee raise') > -1 || n.indexOf('core') > -1) return ['Abs','Hip Flexors'];
  if (n.indexOf('push press') > -1) return ['Shoulders','Triceps','Core'];
  if (n.indexOf('clean') > -1 || n.indexOf('pull') > -1 || n.indexOf('snatch') > -1) return ['Glutes','Quads','Upper Back','Traps'];
  return ['Full Body'];
}

function openExercise(w,d,i){ try { var ex = dayObj(w,d).exercises[Number(i)]; if (!ex) return; var meta = [ex.sets ? ex.sets + ' sets' : '', ex.reps || '', ex.intensity || ''].filter(Boolean).join(' • '); var muscles = (typeof muscleListForExercise === 'function' ? muscleListForExercise(ex.name) : ['Full Body']); $('modalContent').innerHTML = '<h3>'+ex.name+'</h3><p class="muted">'+meta+'</p><div class="list-item"><strong>Targets</strong><div class="modal-targets">'+muscles.map(function(m){ return '<span class="modal-target">'+m+'</span>'; }).join('')+'</div></div><p>'+ex.desc+'</p>'+(ex.note ? '<div class="list-item"><strong>Program note</strong><div class="muted">'+ex.note+'</div></div>' : '')+'<div class="list-block"><div class="list-item"><strong>Why it’s here</strong><div class="muted">'+ex.why+'</div></div><div class="list-item"><strong>Cues</strong><div class="muted">• '+ex.cues.join('<br>• ')+'</div></div><div class="list-item"><strong>Avoid</strong><div class="muted">• '+ex.avoid.join('<br>• ')+'</div></div></div>'; $('exerciseModal').classList.remove('hidden'); $('exerciseModal').setAttribute('aria-hidden','false'); } catch (err) { console.error(err); toast('Could not open exercise details.'); } }
function closeExercise(){ $('exerciseModal').classList.add('hidden'); $('exerciseModal').setAttribute('aria-hidden','true'); }
function populateSelects(){ $('weekSelect').innerHTML = PROGRAM.map(function(w){ return '<option value="'+w.week+'">'+w.week+'</option>'; }).join(''); $('daySelect').innerHTML = DAY_SHORT.map(function(d,i){ return '<option value="'+i+'">'+d+'</option>'; }).join(''); $('weekSelect').value = String(state.activeWeek); $('daySelect').value = String(state.activeDay); }
function init(){ load(); populateSelects(); el.toast = $('toast'); $('weekSelect').addEventListener('change', function(){ state.activeWeek = Number(this.value); state.browseWeek = state.activeWeek; save(); renderAll(); }); $('daySelect').addEventListener('change', function(){ state.activeDay = Number(this.value); state.browseDay = state.activeDay; save(); renderAll(); }); $('importInput').addEventListener('change', function(e){ var file = e.target.files && e.target.files[0]; if (file) importData(file); e.target.value = ''; }); document.addEventListener('click', function(e){ var nav = e.target.closest('[data-nav]'); if (nav) { switchView(nav.getAttribute('data-nav')); return; } var open = e.target.closest('[data-open-ex]'); if (open && !e.target.closest('[data-check]')) { var parts = open.getAttribute('data-open-ex').split('|'); openExercise(parts[0], parts[1], parts[2]); return; } var browse = e.target.closest('[data-browse-day]'); if (browse) { state.browseDay = Number(browse.getAttribute('data-browse-day')); save(); renderView('program'); bindStatefulControls(); return; } var active = e.target.closest('[data-active-day]'); if (active) { state.activeDay = Number(active.getAttribute('data-active-day')); save(); renderView('today'); bindStatefulControls(); updateFocus(); return; } if (e.target.closest('[data-close="modal"]')) { closeExercise(); return; } }); document.addEventListener('change', function(e){ var t = e.target; if (t.matches('[data-check]')) { var parts = t.getAttribute('data-check').split('|'); state.checks[checkKey(parts[0], parts[1], parts[2])] = t.checked; save(); renderView('today'); bindStatefulControls(); renderView('home'); renderView('program'); updateFocus(); } }); renderAll(); switchView(state.activeView || 'home'); }
document.addEventListener('DOMContentLoaded', init);
